[roll] Roll fuchsia [beads][rust] Fix mypy errors in comparison scripts and deps
Note I'm switching a lot of list to Sequence because list is invariant,
which doesn't work well with type unions (e.g. str | Path), I'm seeing
mypy errors like:

```
build/api/ninja_artifacts.py:89: error:
Argument 1 to "run_command" of "CommandRunner" has incompatible type
"list[str]"; expected "list[str | PathLike[Any]]"  [arg-type]
                [str(self.ninja), "-C", str(self.build_dir)] + cmd,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/api/ninja_artifacts.py:89: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
build/api/ninja_artifacts.py:89: note: Consider using "Sequence" instead, which is covariant
````

Original-Bug: 478707341
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1575074
Original-Revision: fcc58ee661b59748a75a40041d4a075765532296
GitOrigin-RevId: ba5dc6da0613cd66a05aad9154a1233bee51f2f7
Change-Id: Ic8aac1f347d970fc5644f88919af2be0e2defe7c