[roll] Roll fuchsia [fx][build] Remove support for Ninja options + minor fixes.
In preparation for future CLs that will add support to building
Bazel targets directly, remove the special handling for Ninja
options in `fx build`, forcing the user to pass them after the
`--` option. Doing this was supported with a warning stating
that this will become an error. This CL implements that.

For example, before this CL:

```
$ fx build -t deps sdk:core
WARNING: Use -- to pass Ninja-specific options, as in:
WARNING:   fx build  -- -t deps sdk:core
WARNING: This warning will soon become an error.
sdk:core: deps not found
```

After the CL:

```
$ fx build -t deps sdk:core
ERROR: Unsupported option -t, see 'fx help build' for details.
```

+ Print an error message when running on MacOS, now that we
  removed official support for building Fuchsia on it.

+ Also use ${HOST_OS} instead of $(uname) which is slightly faster.

+ Address a few issues found with `shellcheck`, i.e.:

```
In tools/devshell/build line 125:
    echo "$(wc -l <"${NINJA_LOG_FILE}" 2>/dev/null)"
         ^-- SC2005 (style): Useless echo? Instead of 'echo $(cmd)', just use 'cmd'.

In tools/devshell/build line 381:
  local -i ninja_log_line_count_before="$(count-ninja-log-lines)"
           ^-------------------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.

In tools/devshell/build line 481:
  local -i ninja_log_line_count_after="$(count-ninja-log-lines)"
           ^------------------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.

For more information:
  https://www.shellcheck.net/wiki/SC2155 -- Declare and assign separately to ...
  https://www.shellcheck.net/wiki/SC2005 -- Useless echo? Instead of 'echo $(...
```

Original-Bug: 42084668
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1206184
Original-Revision: c77b0293ca76c957e32f22df332db836a02ddcba
GitOrigin-RevId: fbbe8e400bea6ab6c32a038e1454cd9d5c7a97c9
Change-Id: I7c4e6205f355806ad25d82037bcea344180c87d8