[roll] Roll fuchsia Revert "[bazel] Use str(label) where possible"
This reverts commit dfb003283090a6294b49accc9a1fdbe5d480e258.

Reason for revert: break local build

This break the build when args.gn contains:
product_assembly_overrides_label = "//local:include_ssh_keys"

Bazel error:
Repository rule assembly_developer_overrides_repository defined at:
  /usr/local/google/home/qsr/programmes/fuchsia/out/fuchsia_internal.arm64-balanced/gen/build/bazel/workspace/build/bazel/assembly/developer_overrides/repository_rules.bzl:72:58: in <toplevel>
ERROR: /usr/local/google/home/qsr/programmes/fuchsia/out/fuchsia_internal.arm64-balanced/gen/build/bazel/workspace/build/bazel/assembly/developer_overrides/repository_rules.bzl:11:63: An error occurred during the fetch of repository '+_repo_rules6+assembly_developer_overrides':
   Traceback (most recent call last):
	File "/usr/local/google/home/qsr/programmes/fuchsia/out/fuchsia_internal.arm64-balanced/gen/build/bazel/workspace/build/bazel/assembly/developer_overrides/repository_rules.bzl", line 40, column 50, in _generate_developer_overrides_repository_impl
		target_lines = _make_overrides_target(override_label)
	File "/usr/local/google/home/qsr/programmes/fuchsia/out/fuchsia_internal.arm64-balanced/gen/build/bazel/workspace/build/bazel/assembly/developer_overrides/repository_rules.bzl", line 11, column 63, in _make_overrides_target
		"    overrides_path = \"@gn_targets%s\"," % str(label).remove_prefix("@@"),
Error: 'string' value has no field or method 'remove_prefix' (did you mean 'removeprefix'?)

Original change's description:
> [bazel] Use str(label) where possible
>
> Use `str(label)` when a string version of a label is needed rather than
> building a string label from the label's `package` and `name`.
>
> The resulting string begins with `@@//` rather than `//`.
>
> NO_IFTTT=This is a Bazel-specific change.
>
> Change-Id: I304c59d24946b831ff3839bb4ce685c504173d69
> Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1561903
> Commit-Queue: David Turner <digit@google.com>
> Reviewed-by: David Turner <digit@google.com>
> Fuchsia-Auto-Submit: David Turner <digit@google.com>

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1563193
Exempt: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Revision: 06304155f6b09db7e9828938d65361bafdfd74ab
GitOrigin-RevId: c67a114d0453521b2259558c6ad6c6d48db17977
Change-Id: I0812f20c0c5ac92923aa778e914f258f96fcb563