[roll] Roll fuchsia [flake][components][bootfs] Fix flake
This test launches component_manager and then checks some state. It
assumes that component_manager continues running. However, this
assumption is not necessarily correct, because the root component it is
launching (hello_world) exits, whereupon component_manager will exit as
well. If component_manager exits before the test completes, something
else in the test may bind to an exposed capability (RealmQuery), causing
component_manager to restart. When it restarts, it does so implicitly
without its bootfs vmo argument, triggering this panic:

```
[00718.630551][1113][1198][coll:auto-48b1cae71e3d3107] WARN: thread 'main' panicked at ../../src/sys/component_manager/src/main.rs:108:51:
[00718.630595][1113][1198][coll:auto-48b1cae71e3d3107] WARN: Failed to create Rust bootfs: InvalidHandle { handle_type: BootfsVmo }
```

To fix, switch to a different root component (trigger.cml) that does not
exit.

Multiply: fuchsia-boot-resolver-integration-tests: 200

Original-Fixed: 356731816
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1096960
Original-Revision: 92b25dacd956e375fc35b56b8bff5a91ff75520c
GitOrigin-RevId: 3a56a2edc7f4e2c9f33d0edb0e80ced28548afa3
Change-Id: Iff7ac77833c77ba6cc4b33d130e274994b05a321