[roll] Roll third_party/pigweed pw_unit_test: Fix -Waddress warning when verifying RUN_ALL_TESTS
When Google Test back-end is used for pw_unit_test GCC reports warning
as follows:

pw_unit_test/public/pw_unit_test/framework.h:181:30: error: the address of 'int RUN_ALL_TESTS()' will never be NULL [-Werror=address]

This happens only with Google Test back-end, because pw_unit_test uses
"#define RUN_ALL_TESTS() ..." and in such case the static_assert is not
used.

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/243133
Original-Revision: a4636bc83d6905cb252a65d19eab4ec2478af42b
GitOrigin-RevId: ac89f390430809c5f6def0df485b553a60ea2dd3
Change-Id: I5447a49c89b6a58fc254830fe6ccffc7fecb1b62