[roll] Roll fuchsia [fx][flash] Fix `fx flash` " Unknown Ninja path" error.
Fix an annoying error when invoking `fx flash` that looks like:

```
ERROR: Unknown Ninja path: products/minimal:product_bundle.vim3
```

- Since `fx build <label>` now works properly use it. The error
  came from the use of <label_without_slash_slash_prefix>, which is
  a GN "convenience alias" in the Ninja build that is no longer
  supported.

+ Fix parsing of product_bundles.json to extract the right label
  when a main_pb_label is set in args.gn.

+ Remove an un-necessary call to `fx-run-command build <artifact_path>`
  since the script already calls `fx get-flash-source --build` when
  `$build` is `true`, which already ensures that the artifacts are
  refreshed / built.

+ Minor shellcheck issues addressed:

  - Use fx-command-stdout-to-array to preserve spaces in line
    outputs, for safety and properly handle errors.

  - Fix problematic quoting of jq_filter value that could break
    on spaces.

  - Removed now unused variables, add directives to ignore
    source inclusion warnings.

Original-Fixed: 407107908
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1238368
Original-Revision: c0bce28ca81ac4177eeb1daa337eabe0e89a2f7d
GitOrigin-RevId: ec66cdcc892dc3f352e090e4f74f996bf195be09
Change-Id: I7e20620fc03238da322ce303750e802ac50a82eb