[roll] Roll fuchsia [build][dtc] Restructure dtc compilation and parse errors
This simplifies the dtc actions by removing dtc.sh and moving to a
python scrupt that handles calling 'dtc' and also parses errors &
warnings to provide additional context.

Example:
```
Error: gen/path/to/a/dtsi/dts-example.dtsi:1.10-17 syntax error
FATAL ERROR: Unable to parse input tree
    1: &reserved-memory {
                ^---- syntax error
    2:  gpu_region: gpu_region@0 {
    3:   reg = <0x00 0x01234567 0x00 0x2000>;
    4:   no-map;
    5:  };
    6: };
```

This provides context for the error along with an indicator of the exact
line and character the error occurs.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1213986
Original-Revision: f70fd0b05e862547e705f95cd931b142e8ffaa04
GitOrigin-RevId: e3e647f8960fb2e65a5f400b2a90f6dc0045b1e0
Change-Id: Ib11b2ae6816af0425e29576b2606382a9bea6234