[roll] Roll fuchsia [bazel_sdk][tests] Update to platforms version 0.0.10
Update the version of the @platforms repository being used.
Without that, the following error occurs when trying to run
`bazel` directly in `//build/bazel_sdk/tests`:

```
ERROR: Error computing the main repository mapping: at /usr/local/google/home/digit/.cache/bazel/_bazel_digit/fec004571c1331a01694de96006458ce/external/fuchsia_workspace/fuchsia/deps.bzl:22:5: at /usr/local/google/home/digit/.cache/bazel/_bazel_digit/fec004571c1331a01694de96006458ce/external/fuchsia_workspace/fuchsia/workspace/rules_fuchsia_deps.bzl:13:6: Label '@@platforms//host:extension.bzl' is invalid because 'host' is not a package; perhaps you meant to put the colon here: '@@platforms//:host/extension.bzl'?
```

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1127253
Original-Revision: d2eb259f9bebad2fe107cfb2245ba30fca1fccb7
GitOrigin-RevId: 863c2a8d3b11b571e097f61bbb7457e6ca2a80c6
Change-Id: I13bae1d2a4a318d56a784976ac882c17bf9871d0