[roll] Roll fuchsia [fx] Verify effectiveness of `-d`.
Check if `-d` is ever overridden by a ffx configuration level default
target, and fail early if that's the case.

Example:
```
❯ fx -d fx-device serve
ERROR: The build level device "fx-device" is being overridden by the user level device "ffx-device".
ERROR: Here are all of the ffx default values set: [
  "ffx-device",
  [
    "fx-device"
  ]
]
ERROR: Please run `ffx target default unset; ffx target default unset --level global` to fix this.
```

Also removes `TEST_getdeviceaddr_name_looks_like_ipv4` since the
expected behavior of this test doesn't align with how ffx works in
reality (i.e `fx -d 1.1.244 ffx target default get` yields `1.1.244`
instead of `127.0.0.1`).

Diff of HEAD^ vs HEAD of this CL for non-CQ tests:
https://diff.googleplex.com/#key=PElcE3cttVvE

Original-Fixed: 398268415
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1214024
Original-Revision: 1c3558092d9f1e905f089478ac30da63c567c738
GitOrigin-RevId: 127e1f52115382ffe31697cbc7c1445f0834e2c2
Change-Id: I4bf2347aa27299731b73ec6d030078989b94334b